trigger:
  - main

variables:
  buildConfiguration: 'Release'
  vmImageName: 'vs2017-win2016'
  workingDirectory: '$(System.DefaultWorkingDirectory)/Portfolio.ContactForm'
  functionAppName: 'favelidapscontactform'
  azureSubscription: 'e86d34ea-25ef-4288-8ffb-5baaea87a61b'

stages:
  - stage: Build
    displayName: Build Stage

    jobs:
      - job: Build
        displayName: Build Project
        pool:
          vmImage: $(vmImageName)
        
        steps:
          - task: DotNetCoreCLI@2
            displayName: Restore Project
            inputs:
              command: 'restore'
              projects: '**/*.csproj'
            
          - task: DotNetCoreCLI@2
            displayName: Build Project
            inputs:
              command: 'build'
              projects: '**/*.csproj'
              arguments: --configuration $(buildConfiguration)

          - task: DotNetCoreCLI@2
            displayName: Run Unit Tests
            inputs:
              command: 'test'
              projects: '**/*UnitTests/*.csproj'

          - task: DotNetCoreCLI@2
            displayName: Publish Project
            inputs:
              command: 'publish'
              publishWebProjects: false
              projects: '**/*.csproj'
              arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)'
              zipAfterPublish: True

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact'
            inputs:
              PathtoPublish: '$(build.artifactstagingdirectory)'
  
  - stage: Deploy
    displayName: 'Deploy Portfolio.ContactForm'
    dependsOn: Build
    condition: succeeded()

    jobs:
      - deployment: Deploy
        displayName: Deploy Portfolio.ContactForm
        environment: Production
        pool:
          vmImage: $(vmImageName)
        
        strategy:
          runOnce:
            deploy:
              
              steps:
                - task: AzureKeyVault@1
                  inputs:
                    azureSubscription: '$(azureSubscription)'
                    KeyVaultName: 'willvelidakeyvault'
                    secretsFilter: '*'
                    runAsPreJob: false

                - task: AzureRmWebAppDeployment@4
                  displayName: 'Deploy Azure Function'
                  inputs:
                    azureSubscription: '$(azureSubscription)'
                    appType: functionApp
                    WebAppName: $(functionAppName)                   
                    package: '$(Pipeline.Workspace)/drop/Portfolio.ContactForm.zip'
                    appSettings: '-FUNCTIONS_WORKER_RUNTIME "dotnet" -FUNCTIONS_EXTENSION_VERSION "~3" -FunctionsOptions:ExceptionRecipientEmail "willvelida@hotmail.co.uk" -FunctionsOptions:ExceptionRecipientName "Will Velida" -FunctionsOptions:SendGridAPIKey "$(sendgridapikey)" -APPINSIGHTS_INSTRUMENTATIONKEY "2fc597df-fc6b-4b20-ac9c-ee7240b70704"'
                    enableCustomDeployment: true
                    RemoveAdditionalFilesFlag: true 


